 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hotels", type: :request do
  # Hotel. As you add validations to Hotel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hotel.create! valid_attributes
      get hotels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hotel = Hotel.create! valid_attributes
      get hotel_url(hotel)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hotel_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hotel = Hotel.create! valid_attributes
      get edit_hotel_url(hotel)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hotel" do
        expect {
          post hotels_url, params: { hotel: valid_attributes }
        }.to change(Hotel, :count).by(1)
      end

      it "redirects to the created hotel" do
        post hotels_url, params: { hotel: valid_attributes }
        expect(response).to redirect_to(hotel_url(Hotel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hotel" do
        expect {
          post hotels_url, params: { hotel: invalid_attributes }
        }.to change(Hotel, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hotels_url, params: { hotel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hotel" do
        hotel = Hotel.create! valid_attributes
        patch hotel_url(hotel), params: { hotel: new_attributes }
        hotel.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hotel" do
        hotel = Hotel.create! valid_attributes
        patch hotel_url(hotel), params: { hotel: new_attributes }
        hotel.reload
        expect(response).to redirect_to(hotel_url(hotel))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hotel = Hotel.create! valid_attributes
        patch hotel_url(hotel), params: { hotel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hotel" do
      hotel = Hotel.create! valid_attributes
      expect {
        delete hotel_url(hotel)
      }.to change(Hotel, :count).by(-1)
    end

    it "redirects to the hotels list" do
      hotel = Hotel.create! valid_attributes
      delete hotel_url(hotel)
      expect(response).to redirect_to(hotels_url)
    end
  end
end
